### ISSUE TITLE
Tag and Category Link Broken in Paging

### ISSUE THREAD

**Issue by berviantoleo** [Arsfiqball/hexo-theme-best-friends#6]
How to produce:

1. Open Archives
2. Open any Tag or Category
3. Go to Number Page.

Expected Link:

`{root.url}/{tag.link}`

Real output:

`{root.url}/{tag.link}/{tag.link}`

**Comment by Arsfiqball** [comment]
Work on it.
Thank you @berviantoleo :)

**Comment by berviantoleo** [comment]
Great
